# Site settings
title: Daraul
email: thurst306@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Daraul can build you your website, setup your hosting and even your web application.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daraul.com" # the base hostname & protocol for your site
github_username:  daraul 
behance_username: daraul

# Build settings
markdown: kramdown
